### ISSUE TITLE
Full screen window is off by one pixel

### ISSUE THREAD

**Issue by pkozuchowski** [WinMerge/winmerge#1296]
When WinMerge is on full screen, it's off by one pixel on the right from the edge of screen. That means if I move mouse exactly to the corner of my window and click, I will close not WinMerge, but the window behind it.

**Comment by sdottaka** [comment]
WinMerge doesn't have a full-screen mode like web browser, but what does "full screen" mean?

I couldn't reproduce the problem even if I maximized the WinMerge window as below.

![image](https://user-images.githubusercontent.com/98126/163997211-aaf5e9f8-d838-46d3-b86d-c95efb58e07b.png)

**Comment by pkozuchowski** [comment]
Sorry, by fullscreen I mean maximize by clicking on the center icon at the top right corner. I think this may be related to multi-monitor setting - this issue occurs on my main, center monitor when there's another screen on the right. 

Here's display configuration:
![image](https://user-images.githubusercontent.com/4470967/164018315-684c924f-a40c-44f7-9cfc-701f7d813a4e.png)
![ezgif-1-a7bdec74f8](https://user-images.githubusercontent.com/4470967/164021472-34a65d5b-6200-467b-9cf5-90a6aead1fe6.gif)

Phone recording because my gif recorder wouldn't record area close to the top of the screen. 
This issue does not occur in other programs.

**Comment by sdottaka** [comment]
Thank you for the info.
I tried to reproduce it using two monitors(left: 1366x768, right: 1280x600), but I couldn't reproduce this problem.

This problem seems to occur depending on the environment, so please let me know if you know the conditions that do not cause the problem in your environment.

**Comment by Gitoffthelawn** [comment]
I thought that I perhaps experienced this issue a couple times in the past.  Each time, I was multitasking, so I figured I simply missed the little 'x' box in the corner, as I was focused on many things at once.  But, given this issue report, I thought I would spend a few minutes and perform some testing.  I tested WinMerge for this specific issue on a couple multi-monitor systems, and I couldn't replicate the issue.

So I agree with @sdottaka that additional system-specific details of what conditions cause it to happen, and not happen, will be helpful to determine the cause and generate a fix.

If I ever experience the issue again, I'll be sure to visit this issue report again and post additional details.

**Comment by pkozuchowski** [comment]
I can't reproduce it anymore today....
I'm not sure anymore why or when it happens, it just happens sometimes. I will play with it a bit more and see if I can find way to reproduce this once the issue will appear again.

**Comment by MiltenPlescott** [comment]
I can successfully reproduce this issue on WinMerge version `v2.16.42.1` on Windows 10 22H2. I have 2 displays in `Extend these displays` mode.:
- `#1` - a laptop screen set to 1920x1080 at 125% scaling
- `#2` - a monitor set to 1920x1080 at 100% scaling

The issue seems to depend on which of these 2 displays is set to be my `main display` in windows settings:
- `#1` is main display:
    - there's no gap on the `#1`
    - there is a 1 pixel gap on the `#2`
- `#2` is main display:
    - there's no gap on the `#2`
    - there's a 1 pixel gap on the `#1`

**Comment by chadbaldwin** [comment]
I don't know if this is the same issue, but I'm experiencing a similar problem with same symptoms as @MiltenPlescott described. However, it is much more extreme in my case.

My monitor setup is a bit odd...
![Image](https://github.com/user-attachments/assets/fbfef7b9-2857-4e5f-85d9-7933c12f161e)

Monitor 4 is set up as the primary.

WinMerge has no issues going full screen on the primary monitor (4). However, if I try to maximize it on any of the other monitors (1,2,3), the entire menu bar is cut off.

![Image](https://github.com/user-attachments/assets/0dbb1cdf-ed28-4329-b1a3-2a5c7ab9aeb1)

**Comment by sdottaka** [comment]
If you are using an older version of WinMerge, could you try the latest version, 2.16.46?

**Comment by chadbaldwin** [comment]
@sdottaka Well I'll be damned. It's working now. Sorry about that...

I didn't realize I was a couple versions behind (2.16.44). I installed using winget and I _just_ installed WinMerge a week ago on my new computer, so I thought I had the latest and I didn't expect an issue I've had for months to suddenly be fixed in the last few days 😂

**Comment by SamHasler** [comment]
I'm still getting this with 2.16.46. A few clues:

I have 4 screens. A laptops screen at 250% scale, and 3 external monitors at 100% scale. I can only see the issue on the monitors, not the laptop screen. The laptop is my primary monitor, it's top edge is (virtually) also  above all the other monitors top edge:

![Image](https://github.com/user-attachments/assets/a4371e21-b12c-4d32-9d18-940033fb8670)

**Comment by sdottaka** [comment]
I think I was able to reproduce this issue.
Perhaps to resolve this issue, WinMerge needs to be modified to be Per Monitor High DPI Aware.

![Image](https://github.com/user-attachments/assets/268223d4-c1eb-4b29-af45-ae44d673b038)
