### ISSUE TITLE
WinMerge 2.16.50.0 is just closing at start of execution when comparing 2 text files of size 331,948,032 bytes.

### ISSUE THREAD

**Issue by E6NikonF5** [WinMerge/winmerge#2905]
I converted a WAV binary file to text using xxd.exe resulting in 2 text files of size 331,948,032 bytes. When WinMerge version 2.16.50.0 started, it just
closed and did not continue and totally exited out. Is 331,948,032 bytes already too large for WinMerge 2.16.50.0 to compare?

The files even failed to upload!

The reason why I converted the binary WAV files to Text contain Hex values is that WinMerge can easily compare text files
instead of binary files. The Text files can be compared by "Meld" but "Meld" does not even output any list or display the 
differences found in the 2 text files being compared.

If the size of the text files cannot be handled by WinMerge 2.16.50.0, then there should be an error message instead of 
WinMerge just exiting out.

I can open the 2 files using Notepad as uploaded. Uploaded images files names are:
1)  01-NoTimeForTalk.png
2)  01-NoTimeForTalkX.png

<img width="1072" height="771" alt="Image" src="https://github.com/user-attachments/assets/a0e28ce5-30fa-4f2e-ad76-6766033c253a" />
<img width="1072" height="771" alt="Image" src="https://github.com/user-attachments/assets/a05c3e74-5240-4a26-9963-f8c3b46a9716" />

So what is the maximum size of Windows text files that can be handled by WinMerge 2.16.50.0?

Edwin

**Comment by sdottaka** [comment]
Thank you for the report.

This is a regression in WinMerge 2.16.50.
When comparing very large files, the message box asking whether to show full content has a bug: if you select Yes, WinMerge crashes.

It’s not caused by the file size itself. We’ll fix this in the next release.

**Comment by sdottaka** [comment]
Duplicates of #2874

**Comment by E6NikonF5** [comment]
The version of Windows 10 is Windows 22H2 (latest and greatest) and I could
NOT even see any message box and WinMerge
just closes. Without seeing the message box, I could even select the "YES"
option.

This is my version of Windows 10 (the latest version and 1 Windows update,
my Windows 10 will be Windows 11 as only the WIndows 11
features are NOT running in my Windows 10). I am staying at Windows 10
because I have so many Audio and Video apps and other Application
Development tools and I do not want any apps already installed and working
NOT to work.
     [image: image.png]

Thank you for your quick response.

Edwin

**Comment by sdottaka** [comment]
If the option "Comparing large files ..." is checked in the Options window (MessageBoxes section), the message box will not be shown.
<img width="1850" height="1174" alt="Image" src="https://github.com/user-attachments/assets/4d829139-1131-48eb-b769-36f5f9cee8e7" />

**Comment by E6NikonF5** [comment]
This is my WinMerge Options:
      [image: image.png]

When I compare the 2 Text files I stated in my previous email, the modal
message still not being rendered.

My PC workstation is a Lenovo P620 Workstation as shown with 128GB of
Hardware memory:
     [image: image.png]

Can I give you a physical address so I can mail a  CD-R of the 2 Test files
that I cannot upload to
GirHub?

Edwin

**Comment by sdottaka** [comment]
When replying by email, the attached images are not visible on GitHub, so I couldn’t check them.
I assume the “Compare large files…” checkbox was not enabled—is that correct?

Sending a CD-R would be cumbersome, so could you please provide the following instead:

How to obtain data that reproduces the issue (any format is fine).

How to convert the data to text.

How you ran the comparison in WinMerge (e.g., drag & drop the two files, or used the Explorer context menu).

**Comment by E6NikonF5** [comment]
Yes, in my WinWerge setup, the checkup by default is NOT checked.

To reproduce the data, you need to have 2 songs in WAV files at least 2
complete songs.

When comparing WAV file(s), I also have the same result as comparing the
WAV files
converted to Text files using xxd.exe. .

xxd.exe is the only way to convert the WAV files to Text and I used it with
Meld (which
also produces nothing like WInMerge).

I have to install, xxd (open source in Github) -
      https://github.com/ckormanyos/xxd
      get the latest 1.2 version -
https://github.com/ckormanyos/xxd/releases/tag/v1.2

If using just xxd, you have to add the xxd.exe to C:\Program Files\xxd\,
add to Environment Variables
just like what I did for yt-dlp:
     [image: image.png]

Convert the 2 WAV files to Text file using MS-DOS command prompt using
xxd.exe as shown:
.      [image: image.png]

Thanks for the reply.

Edwin

**Comment by sdottaka** [comment]
When I compare files in WinMerge 2.16.50 (xxd-converted text files of 2–3 GB or WAV files of 600–700 MB), a message box appears.
If your comparison method is different, could you please let me know?
![Image](https://github.com/user-attachments/assets/65b4b76b-46a1-4eca-8961-c6cc0f672189)

**Comment by E6NikonF5** [comment]
My WinMerge Comparison just puts out this Modal window to Continue because
of large memory usage and I will click "Yes"
     [image: image.png]

and the problem I stated that WinMerge just closes happens.

My Windows 10 22H2 (latest and greatest version) has 128GB of memory, is
that NOT enough?
      [image: image.png]
What is your WIndows 10 total hardware memory.

When I installed WinMerge it is just the default install with just clicking
all the default options until
WinMerge was finally installed.

Edwin

**Comment by E6NikonF5** [comment]
I even stopped my AdBlocker Ultimate from loading/executing when the PC
first starts, tested WinMerge and
the same WinMerge closing behavior still happens.

Edwin

**Comment by E6NikonF5** [comment]
I downloaded WinMerge 2.16.50 3 days after it was officially published as
shown:
     [image: image.png]

I even downloaded WinMerge again and made a comparison of the last
downloaded I did on July 28, 2025 and the EXE files are IDENTICAL as shown:
      [image: image.png]

That is the reason I asked you the question what is the maximum size of a
BINARY file that winMerge is able to compare because WinMerge EXE is
12,279,808 bytes and WInMerge is able to compare the WinMerge executable
just fine!

Is there an option to check in the WinMerge Main Options to compare binary
files without limits?

Edwin

**Comment by E6NikonF5** [comment]
I compared 2 WAV files (16-bit 44100Hz sampling) and WinMerge was able to
compare it as shown:
      [image: image.png]

When I converted the 2 different WAV files to text files using xxd.exe and
compared the 2 Text files, the
non-display of the modal screen did NOT happen at all.

These are the sizes of the Text files that failed:
     [image: image.png]
Files are:
      [image: image.png]
      [image: image.png]

This is the exact reason why I was asking for any text file limitation that
can be accommodated by WinMerge!

Edwin

**Comment by E6NikonF5** [comment]
If you can kindly give me a website that I can upload the 2 Text files and
you can download them.

Otherwise, kindly give me your PO Box address and I will mail a CD-R
containing the 2 Text files. Or do you want it as a USB Thumb drive?.

Thanks.

**Comment by sdottaka** [comment]
So just to confirm, the message box did appear when comparing large files, correct?
If WinMerge closed after you clicked "Yes," that is a bug introduced in 2.16.50.
We will release 2.16.50.2 tomorrow—could you please try it and see if the issue is resolved?

**Comment by E6NikonF5** [comment]
When I made my last test and emailed all my documentation to you, *I did
not even check*
*the checkbox. *

I was able to use WinMerge to compare two 16-bit 44100Hz WAV files
directly. *There is NO Modal that *
*even displayed for me to Select the "Yes" option but WinMerge was able to
compare.*

Then when I converted the two 16-bit 44100Hz WAV files to become Text files
using xxd.exe, and comparing
the generated Text files using WinMerge, the problem of the Modal DID NOT
even display at all and WinMerge
did not perform a COMPARE AT ALL..

Prior to comparing the two 16-bit 44100Hz WAV files, I was comparing 24-bit
48000Hz sample WAV files
because when I work on WAV files, I have to convert the 16-bit 44100Hz
sampled WAV files to 24-bit
48000Hz sampled files to prevent losses during Audacity plug-in
execution. *When
comparing two 24-bit*
*48000Hz sampled WAV files, the modal that will ask for the "Yes" option IS
NOT even happening at all.*

Edwin

**Comment by E6NikonF5** [comment]
I performed the Test by checking the checkbox "Comparing large files
requires significant memory"
in the WinMerge Options:
      [image: image.png]

When I compare the 2 Text files I used during the first test:
      [image: image.png]
And I still got the "NO Modal' displaying.

Now what is the next move? I asked you for me to send a CD-R containing the
Text files I created
or give me a URL that can accept these 2 Text files that you can download
and perform your tests
using the files I am having trouble with.

Edwin

**Comment by E6NikonF5** [comment]
Kindly upload a 2.16.51 version which is your version in your computer to
Github and I will download it to compare
with the version of 2.16.50 in GitHub I downloaded way back in July 2025.

This is the download of WinMerge in my computer as of July 28, 2025:
     [image: image.png]

I downloaded the current version of 2.16.50 as of today 08/26/2025 from
Github as shown:
        [image: image.png]
and compared it with the July 28, 2025 version I downloaded before *using
kDiff3 (not WinMerge) *
       [image: image.png]
and this is the result (they are* BINARY EQUAL*):
      [image: image.png]

If I compare the same Binary Files using Winmerge 2.16.50 in my computer,
this is the result (they are IDENTICAL):
      [image: image.png]

Using the *original TEXT files that WinMerge is failing*:
      [image: image.png]
   and *comparing them using kDiff3*:
       [image: image.png]
the result is *Kdiff3 is NOT responding*:
      [image: image.png]

Therefore, *kDiff3 and WinMerge cannot handle very large files like AUDIO
WAV files or very large TEXT files.*

I changed WinMerge Options as:
      [image: image.png]
and compare the original Large Text files that are failing as shown:
      [image: image.png]
and now I DO NOT even get any message and WinMerge is just closing.

*The bug is NO Message is coming out from WinMerge when comparing very
large files. kDiff3 is NOT RESPONDING when I compare*
*the same LARGE Text files, but WinMerge should display a message (I
think!).*
*kDiff3 can load those large WAV files but is NOT responding* as shown
above by my kDiff3 comparison?

Edwin

**Comment by sdottaka** [comment]
Just to make sure I understand correctly — sometimes the message box appears, and sometimes it does not, right?

In WinMerge, files larger than 64 MB are treated as large files, and a confirmation message box should normally be shown when comparing them.
If the message box is not shown, it might be due to the setting I mentioned earlier, or perhaps the file size is actually below 64 MB.

By the way, I’m not able to see any of the images you attached by email.
Could you please check this issue directly on the GitHub site instead?

**Comment by E6NikonF5** [comment]
I will re-enter my last email in GitHub with the images attached inLine.

Github is SO crude that it will not paste the images.

Edwin

**Comment by E6NikonF5** [comment]
Please close the bug I reported. All the other open source compare
utilities like Kdiff3, DiffMerge, Meld
cannot go further and compare the huge Text and WAV file that I was
comparing.

But BeyondCompare can do it and I can just purchase the Standard License
for company large
Binary/Hex Tet files.

Edwin

**Comment by sdottaka** [comment]
Thank you for your report.
This issue has been fixed in version 2.16.50.2, including the crash when clicking "Yes" on the large file dialog.
In the 64-bit version, very large files may still be displayed if enough memory is available, but please note that WinMerge is not optimized for such cases and performance may be limited.
Since you requested it, we will close this issue.

**Comment by E6NikonF5** [comment]
When is WinMerge 2.16.50.2 be released so I can download it.

As I stated, I have 128GB of hardware memory and my Windows 10 is not even
reaching that 128GB. I still have to purchase another 128GB
this Christmas. BeyondCompare was able to compare both WAV and TEXT files
but it took longer for the TEXT files to be compared
as it took BeyondCompare more than an hour to finish.

Please reply.

Edwin

**Comment by E6NikonF5** [comment]
I just saw WinMerge 2.16.50.2 already available at winmerge.org and I will
download it and
will email you the results.

Edwin

**Comment by E6NikonF5** [comment]
I just tested WinMerge 2.16.50.2 and resulted in responding that the 2 HUGE
Text files
are different.
      [image: image.png]

That would be fine as all the other Open Source software like "kDiff3" is
NOT even
responding and so in Meld.exe.

I can purchase Beyond Compare for comparing large WAV and TEXT files.

You can close my issue.

Thank you for the new release.

Edwin

**Comment by sdottaka** [comment]
Thank you for confirming the fix in 2.16.50.2.
We’re glad the issue is resolved.

**Comment by E6NikonF5** [comment]
It is displaying the modal pop-up but there is still the issue that the
compare is not happening
after the Modal pop-up is displayed.

As I stated, I will purchase Beyond Compare because Beyond Compare can
perform the
comparison of very huge binary and text files.

I just wanted the issue closed because all the Open Source software that I
have tested *kdiff3, Meld, etc"
are also NOT responding when comparing the very BIG files I want to compare
and this is the reason
why I stated to close WinMerge because I will purchase the standard license
for Beyond Compare as
Beyond Compare is able to perform comparison of very huge text and binary
files.

Edwin

**Comment by sdottaka** [comment]
It seems there is some confusion, as you reported both that the comparison completed and that it did not. Not being able to see the attached images may have contributed to this.

For your information, this issue has already been closed. Beyond Compare is a more robust tool for comparing very large text or binary files, and if you have it, it is recommended.

For other users: when using the 32-bit version of WinMerge, there is a 2 GB memory limit, so very large files may not be comparable. In the 64-bit version, files larger than 64 MB will trigger a prompt asking whether to show only the comparison results. Selecting Yes allows comparison without loading the full files into memory, while No loads the full content and may take a long time.

**Comment by E6NikonF5** [comment]
What I meant is that a modal using 2.16.50.2 (which I installed yesterday)
displayed a modal
message stating "The Files are NOT identical" and then stopped comparison.

How come? BeyondCompare still compares and still shows the difference
between the
2 Huge WAV and Text files.

*That is how it confuses people, that NO difference display was shown when
the 2 files are*
*different.* It seems that the WinMerge programmers have no time to
continue the comparison of
the 2 huge WAV or TEXT files.

When I stated that comparison is completed, it completed without doing any
comparison at all without
any display of the difference. *If this is the behavior of WinMerge 2.16.50
and 2.16.50.2, then it should *
*be documented as an alert for the user to know how WinMerge should behave
instead of me just*
*thinking **that it is NOT even doing anything, just closing out without
any comparison being done.*

As I stated, I downloaded the x64 version of WinMerge and *I have 128GB of
memory so memory is *
*NOT an issue as **I install only x64-bit version of software applications*.
I can still install 32-bit Software
applications on a x64-bit of WIndows 10 Pro edition.

This is what my PC has 128GB of memory:
    [image: image.png]
2.16.50 Windmerge was downloaded by me on July 2025 and 2.16.50.2 was just
downloaded
yesterday 08/27/2025.

Since I just found out yesterday that Beyond Compare is better than
WinMerge for comparing
huge WAV and TEXT files, I emailed you that I will purchase BeyondCompare
for comparing
large WAV and TEXT files.

I am a retired Computer Consultant and worked for Nationwide Insurance and
WinMerge was NOT
recommended and we were forced to use Beyond Compare. But I never used
BeyondCompare to
compare huge WAV and TEXT files at work and it is only my hobby of
restoring vinyl records and
CD's that sound BLAND on my stereo system and that is how I found out about
this WinMerge
deficiency. Since after retirement, I only installed Open Source
software like Audacity and its plugins
and did not even have any problems with my other installed Open Source
Source applications except
WinMerge, I did not expect that it cannot handle huge WAV and TEXT files.
It is NOT only WInMerge
that just stops comparison, other file comparison applications kDiff3 and
Meld just freezes and I have
to cancel them using Windows Task Manager.

 When finding out that Beyond Compare has that capability to compare HUGE
WAV and TEXT files
yesterday, I decided to email you to CLOSE the Github Defect as I found the
alternative for HUGE
WAV and TEXT  files which is BeyondCompare.

Edwin

**Comment by sdottaka** [comment]
You may no longer be interested in WinMerge, but just for clarification:

When comparing files larger than 64MB, WinMerge shows a dialog:
“Comparing large files requires significant memory. Show only comparison results (not file contents)?”

If you choose Yes, WinMerge only shows whether the files differ, without loading their contents.

If you choose No, WinMerge attempts to load the contents and display the differences. In this case, like kdiff3 or Meld, it may take a very long time or fail to respond, but it does at least try to show the contents.

As a side note, if you wish to attach images in the future, please post them directly in the GitHub issue tracker (e.g. [#2905](https://github.com/WinMerge/winmerge/issues/2905) instead of email.

**Comment by E6NikonF5** [comment]
I am still using WinMerge but only for 3-way comparison which I use for my
Backup sub-directories and Financial records.

But when it comes to HUGE WAV and TXT files, I will use Beyond Compare.
because of WinMerge limitations.  I already suggested
to Beyond Compare the 3-way compare and their development team is still
working on the 3-way compare.

Edwin

**Comment by E6NikonF5** [comment]
The other reason why I still use WinMerge is the ability to submit batch
compares using MS-DOS command window and
this WinMerge Feature eliminates remembering of prior sub-directories that
users will have to select when launching
WinMerge for each sub-directory.

With the Batch feature, all I have to do is paste this sample MS-DOS
command and 4 WinMerge Pop-up Threads are automatically
launched, This is a sample MS-DOS command that I submit daily (changing
some sub-directories names of course).
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"C:\Program Files\WinMerge\WinMergeU.exe" "D:\AAAAA_-_2025_1"
"L:\BBBBB_-_2025_1" "F:\CCCCC_-_2025_1"
"C:\Program Files\WinMerge\WinMergeU.exe" "D:\AAAAA_-_2025_1"
"J:\BBBBB_-_2025_1" "K:\P620\D$\CCCCC_-_2025_1"
"C:\Program Files\WinMerge\WinMergeU.exe" "D:\AAAAA_-_2025_1"
"N:\BBBBB_-_2025_1" "Q:\CCCCC_-_2025_1"
"C:\Program Files\WinMerge\WinMergeU.exe" "D:\AAAAA_-_2025_1"
"P:\BBBBB_-_2025_1" "O:\CCCCC_-_2025_1"
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

I keep multiple backups (in thumb drives) in case of failure I can still
access all my files using another computer.

Edwin

**Comment by sdottaka** [comment]
So, just to confirm my understanding: when you selected “No” in the dialog “Comparing large files requires significant memory. Show only comparison results (not file contents)?”, WinMerge either crashed or hung, and therefore was unusable — is that correct?

**Comment by E6NikonF5** [comment]
When I compared the 2 HUGE Text files using 2.16.50.2, all I get is a Modal
stating
"Files are DIFFERENT" and then NO further comparison is made.

I don't see anything about asking for a "YES" or "NO" question.

Edwin

**Comment by E6NikonF5** [comment]
When I compare two huge WAV files that are identical, all I got
is a modal stating "Selected files are identical." with an "OK" button to
close
the modal and there is NO modal asking for a "YES" or "NO" response,

I forgot to state in my first email response when comparing 2 HUGE files
that are different, the modal
stating "Files are different" also has an "OK" button to close the modal
and there is also NO Modal
asking for a "YES" or "NO" response.

If the "YES" or "NO" refers to memory usage, I told you my WIndows 10 Pro
has 128GB of
memory and there is NO modal to ask to continue due to memory constraints.

My other workstation has even more memory which is 256GB of hardware memory.

Edwin

Edwin

**Comment by sdottaka** [comment]
Earlier you mentioned: “I performed the Test by checking the checkbox "Comparing large files requires significant memory" in the WinMerge Options.”
If this checkbox remains checked, the message box “Comparing large files requires significant memory...” will not appear.
Please try unchecking this option.

**Comment by E6NikonF5** [comment]
This is to confirm what you just stated in your last email:.

When the new version 2.16.50.2 came out and installed on my PC, my
testing yesterday 08/29/2025 WinMerge
had the Options checkbox stating:
     *"Comparing large files requires significant memory...” set as CHECKED*
and when I clicked the "Compare"
button in the WinMerge Main or Parent Window, all I get is a small modal
window stating either the message
"The files are Identical" or "The files are different." (based on the
Winmerge Compare process). Since the
message modal contains the "OK" button, I clicked the "OK" button and NO
further comparison was performed.
This is the bug I reported.

I believe the version of 2.16.50 I downloaded last July 28, 2025 was
different from your 2.16.50 version you are
using because the newer version 2.16.50*.2* just came out yesterday
08/29/2025. How did that happen when
*there is **NO .1 version in the WInMerge download website*?  I downloaded
the 2.16.50 WinMerge EXE
yesterday from the WinMerge website and compared it with my July 28, 2025
downloaded version and they
are identical with NO binary/hex differences. You see, I keep generations
of all my downloads and I do not
replace the last downloaded version with the new version, the old version
is always saved/kept on my end
so I can compare EXE downloaded file differences.

*First test (WinMerge Options "Comparing large files requires significant
memory" is UNCHECKED):*
When I removed the checkbox for today's (08/30/2025) test, what I got is a
bigger modal window stating
      "Comparing large files require significant memory..." and "Yes" or
"NO" buttons are shown
for me to make a selection. When I clicked *"NO"*, the modal closed, and in
the main WinMerge
window, the "Compare" button is enabled, so I clicked "Compare" and now *I
can see WinMerge *
*running its compare process and finally the file differences **displayed
in YELLOW (I have 128 *
*GB of hardware memory.).*

*Second test (WinMerge Options "Comparing large files requires significant
memory" is UNCHECKED):*
When I removed the checkbox for today's (08/30/2025) test, what I got is a
bigger modal window stating
      "Comparing large files require significant memory..." and "Yes" or
"No" buttons are shown
for me to make a selection. When I clicked *"YES"*, the modal closed and
the small modal displaying
message "The files are different" came up and I clicked "OK" to close the
pop-up message.
Then the "Compare" button is enabled in WinMerge main screen and I clicked
"Compare" and the big
modal window stating
      "Comparing large files require significant memory..." and "Yes" or
"No" buttons are shown again.
Therefore it is repeating the process for me to re-select "YES" or "NO".

In WinMerge *2.16.50*, whether the WinMerge Options
    "Comparing large files require significant memory" is *checked or
unchecked*,
no further modal was being displayed and WinMerge just closed the main
modal where the
compare files are entered. This is the bug description I reported.

Edwin

**Comment by sdottaka** [comment]
In version 2.16.50.2, when you click No on the
"Comparing large files requires significant memory..." dialog,
you were able to get the expected results (although perhaps less efficient than Beyond Compare) — is that correct?

You also mentioned that clicking Yes only shows a result message without displaying the contents, and you considered this a bug.
Please note that the dialog actually asks: "Show only comparison results (not file contents)?"
If you answer Yes, then showing only the result message is by design, not a bug.

Finally, version 2.16.50.1 does not exist — it was intentionally skipped.
