### ISSUE TITLE
Diff Pane issues

### ISSUE THREAD

**Issue by mdell-seradex** [WinMerge/winmerge#307]
1. While I cannot type directly into the diff pane, I can cut (Ctrl-X, Shift-Del), paste (Ctrl-V, Shift-Ins), backspace and delete, perhaps more.
2. The windows in the pane allow scrolling outside of the currently compared area of the files with no direct way to get back to that region.  The easiest way I have found is to go to the next/previous difference and then go back, but this doesn't work when only one exists.
3. The remainder of the file is still in the diff pane, but it is hidden by, I'm guessing, making the text white.  Because editing can essentially be done in the diff pane, it allows the user to make changes to other parts of the file, however they cannot easily tell they have made a change because those sections are not visible.

Please change the Diff Pane windows to prevent all types of editing, and to prevent scrolling outside of the compared area.

Thank you.

**Comment by vdurante** [comment]
I am facing a weird issue where all the text is white.

![image](https://user-images.githubusercontent.com/5401232/78997017-36fbe500-7b1c-11ea-9c25-b66e7d653d68.png)

**Comment by sdottaka** [comment]
Diff Pane seems to have been maximized.
You can make the Diff Pane smaller by dragging it as follows

![307](https://user-images.githubusercontent.com/98126/78999176-0d2ad880-7b85-11ea-89ab-7d731f618494.gif)


Diff Pane shows only the lines with differences, not the others. (The color of the text is made white so that the text is not visible.)

If you prefer a long horizontal view like Diff Pane, check the [View]->[Split Vertically] menu item.

**Comment by vdurante** [comment]
@sdottaka I didn't notice that, I am sorry. Since I had just upgraded to current version, I thought that was a bug.

**Comment by mdell-seradex** [comment]
Note that in regard to #2, often the differences are more lines than fits in each of the windows in the diff pane.
I can sometimes resize the pane to address this, but not always.
A problem with this is that there is no longer an easy way to get to the first or last line of the specific difference set I am currently comparing, which can slow down productivity.  It is simply too easy to go beyond it.

Thank you.

**Comment by sdottaka** [comment]
I've fixed this issue in commit f0406c1 and 0dd9225.
Thank you for the report.

**Comment by mdell-seradex** [comment]
That is great to hear.  I can't wait to try the new version.  I don't know how often you create official stable releases though.
I also wondered why the 64-bit installer doesn't support per-user installations.  I couldn't find any information on that except that it was enabled in beta? version 2.16.3. Since I only do per machine installs, it really doesn't matter to me.

**Comment by sdottaka** [comment]
CI build artifacts is available for download below.

https://github.com/WinMerge/winmerge/actions/runs/97948144

To support per-user installation, We must create an installer with InnoSetup 6.x. However, when creating an installer with InnoSetup 6.x, some anti-virus software determined it was malware.

For this reason, we are creating an installer with InnoSetup 5.x that does not support per-user installation.

**Comment by mdell-seradex** [comment]
Thank you for the update!  That was really fast!!
I imagine that installer only has had "spot" checking done.  The stable one is likely where you or someone has run through everything to make sure that things don't conflict with each other.
Have you tried [https://virustotal.com](https://virustotal.com) lately to see if InnoSetup 6.x is still an issue?

**Comment by sdottaka** [comment]
Below are the results of the latest installer virus scan.

https://www.virustotal.com/gui/file/371b4321cad6f2bf8f4efae5de3dacf506e4752036d53b4f36e52753cce5add8/detection

It's worse than it used to be, as it was 2 out of 71.

**Comment by mdell-seradex** [comment]
> Below are the results of the latest installer virus scan.
> https://www.virustotal.com/gui/file/371b4321cad6f2bf8f4efae5de3dacf506e4752036d53b4f36e52753cce5add8/detection
> It's worse than it used to be, as it was 2 out of 71.

Well that does suck, but hey, one of those 3 is from Beijing (Jiangmin), so you could think of it as 2 out of 72 now.... :)

**Comment by mdell-seradex** [comment]
I told VirusTotal that it was incorrectly detected as harmful via their "contact us" page:
https://www.virustotal.com/gui/contact-us

**Comment by sdottaka** [comment]
Thank you.

**Comment by mdell-seradex** [comment]
Of course they decided to not be helpful and instead say that we can submit to each individual antivirus vendor. :(.
They did provide a list, but I have not yet followed up.

**Comment by DeeHants** [comment]
A belated response about the virus...
I used to be quite active on the forums, and due to Inno's ease of use, it would often be used as the install tool for malware.
Less than careful anti malware authors would then include the Inno files in the virus signature.
The only real response we had was to repeatedly flag it as a false positive.
I do note that the files above are no longer flagged.

**Comment by mdell-seradex** [comment]
Well that was short.
Unfortunately, @sdottaka, it is once again detected as being infected, but by only one anti-virus (Cybereason).
Hey at least it is down to 1 out of 67.  That is so much better than it was before.
Thank you @DeeHants for checking this out.
Much appreciated.

**Comment by sdottaka** [comment]
The scan result of the latest installer (WinMerge version 2.16.9) created by Inno Setup 6.0.5 is 2 of 69 as shown below.

https://www.virustotal.com/gui/file/cf1b64b3783e6d83af1ddd9417c791959ef78ec4bc3b96818fc913a6ba43c580/detection/f-cf1b64b3783e6d83af1ddd9417c791959ef78ec4bc3b96818fc913a6ba43c580-1599262088

InnoSetup 6 is good, but because of the above situation,
The stable 2.16.8 installer was created with Inno Setup 5.x.

**Comment by sdottaka** [comment]
InnoSetup 5.x can create installers that specialize in per-user installations. (Cannot be selected like Inno Setup 6.x)

For a per-user installation, use WinMerge-2.16.8-x64-PerUser-Setup.exe.

**Comment by mdell-seradex** [comment]
@sdottaka it seems that everyone encounters these kinds of issues eventually.  It is much better now than it was before at 2 of 70 false positives.
I can't tell you how many times I've had to contact antivirus manufacturers because they detected a false positive for our application files.  And since we often enhance them, some were detecting every new release as a problem until they straightened out their detection mechanism.

I do find it very odd that the old scan is only running against 67 antivirus apps, but this new one is running against 70.
Also, I'm unsure why clicking your link re-runs the scan, but this one does not.
[https://www.virustotal.com/gui/file/cf1b64b3783e6d83af1ddd9417c791959ef78ec4bc3b96818fc913a6ba43c580/detection](https://www.virustotal.com/gui/file/cf1b64b3783e6d83af1ddd9417c791959ef78ec4bc3b96818fc913a6ba43c580/detection)

Are you saying that a per-user installer can't be created by Inno Setup 6.x?
I can do that using a Visual Studio Installer Project.  I used to have to edit the MSI using Orca to get it to be the type of installation I wanted, but they fixed that before they officially discontinued it.  But hey, at least they brought it back as an add-in. 🙂

You could always release a new 6.x installer version noting something like the following.
"Some antivirus manufacturers are incorrectly detecting it as infected. Please submit it to your Antivirus manufacturer if you encounter this.  Here is a per user installer that does not experience this..."

It is up to you what you want to do. (obviously 😃)
